### ISSUE TITLE
MP no toma el precio correcto

### ISSUE THREAD

**Issue by yaelduckwen** [mercadopago/cart-virtuemart#12]
Hola estoy utilizando mp en virtuemart3 y cuando va a la ventana de MP no me toma el precio correcto, es como si ignorara los impuestos y solo tubiera en cuenta el precio original.
Dejo fotos, muchas gracias

![image](https://cloud.githubusercontent.com/assets/16963836/18258071/3393d292-73a5-11e6-8aa4-02f65cbc7645.png)

![image](https://cloud.githubusercontent.com/assets/16963836/18258077/4f519d02-73a5-11e6-8410-1a3d749092a4.png)

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen, que tal?

Como fue configurado el impuestos para simular el mismo error.

Slds,

**Comment by yaelduckwen** [comment]
Hola @gmatsuoka  , todo bien gracias.
Es un simple impuesto del 10%. La idea es que si el usuario escoge el método de pago MP, se le agregue un 10% y ese numero es el que figure a pagar.
Si escoge otro método de pago se le descuenta ese 10%.

Las opciones de "Tipo de operación aritmética" tienen algo que ver?

![image](https://cloud.githubusercontent.com/assets/16963836/18412592/95d422ec-7768-11e6-8d8f-0229c7673048.png)

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen, 

Hicimos un pull request. Puede descargar e instalar esta nueva versión?

Slds,

**Comment by yaelduckwen** [comment]
@gmatsuoka Muchas gracias! Da gusto trabajar con desarrolladores tan rápidos de respuesta.
Saludos
