### ISSUE TITLE
MP solo figura como forma de pago si esta sólo o hay 3 métodos

### ISSUE THREAD

**Issue by yaelduckwen** [mercadopago/cart-virtuemart#13]
Hola, mi idea es mostrar dos metodos de pago: MP y Pago en efectivo.
Pero cuando los activo pasa algo raro, MP solo figura como forma de pago si es el único método de pago o si hay dos metodos mas ademas mp, nunca si son solo dos metodos.

Ejemplo:
**MercadoPago como método único: (noten que pone un radio button como si pensara que hay otras opciones)**

![image](https://cloud.githubusercontent.com/assets/16963836/18258336/f46e097a-73a9-11e6-85f1-eaf1d0b18975.png)

**MercadoPago junto a dos métodos mas**

![image](https://cloud.githubusercontent.com/assets/16963836/18258317/9b59b28a-73a9-11e6-8eea-a46e9f80e222.png)

**MercadoPago junto a un método mas (este es el que falla)**

![image](https://cloud.githubusercontent.com/assets/16963836/18258346/2c4c0fc2-73aa-11e6-8e61-0eae52748465.png)

Estoy usando Joomla 3, VM3 y la ultima versión de su plugin.
Muchas gracias

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen , todo bien?

Ese error ocurre con un método especifico? o siempre que es Mercado Pago + otro método?

Slds,

**Comment by yaelduckwen** [comment]
@gmatsuoka  Con cualquier metodo, y siempre que es Mercado Pago + otro método

**Comment by restodo** [comment]
Me ocurre el mismo problema. Estoy usando Virtuemart 3.0.16

**Comment by restodo** [comment]
Encontré la solución, al plugin le falta la función plgVmOnCheckAutomaticSelectedPayment.
Tomé esa función del plugin Standard de pago y la pegué en el archivo mercadopago.php.
Les adjunto el archivo corregido (comprimido) para que puedan realizar la modificación en el productivo.

@yaelduckwen entrá a /plugins/vmpayment/mercadopago , luego hacete backup de mercadopago.php y copia el que subí.
[mercadopago.php.zip](https://github.com/mercadopago/cart-virtuemart/files/470949/mercadopago.php.zip)


Saludos!

**Comment by yaelduckwen** [comment]
@restodo sos un capo del universo! Muchas gracias!!!
@gmatsuoka Estaria bueno que lo implementaran en el código oficial esto.
Gracias y saludos.

**Comment by gmatsuoka** [comment]
@restodo, Gracias por la ayuda!!
@yaelduckwen, Fue implementado! Muchas gracias
Slds,
