### ISSUE TITLE
Mercado Pago Membership Pro y Events Booking

### ISSUE THREAD

**Issue by AlejandroPascoli** [mercadopago/cart-virtuemart#14]
Hola como estás estoy desarrollando el plugin de MP para Events Booking  "Joomla" sistema de eventos, y algo no me cierra, donde puedo en MP hacer unas preguntas, si tienes algún enlace me lo podrías enviar? gracias.

**Comment by gmatsuoka** [comment]
Hola @AlejandroPascoli, todo bien?

Puedes hacer las preguntas en el Forum de Mercado Pago.

https://www.mercadopago.com.br/developers/es/community/

Slds,
