### ISSUE TITLE
not working / can't be installed

### ISSUE THREAD

**Issue by burgerberg** [mercadopago/cart-virtuemart#17]
The extension can't be installed via the instructions provided.

The reason is that it is missing an installation.xml file (containing extension type, version and method...)

Without a .xml file, Joomla! won't recognize the extension and the installation will fail.

**Comment by gmatsuoka** [comment]
Hello, how are you?

We did a pull request (#18) fixing this bug, you can make a new test?

Best regards!

**Comment by burgerberg** [comment]
Awesome, its fixed, thank you ! !
=)
=)
