### ISSUE TITLE
setup redirects to frontend

### ISSUE THREAD

**Issue by weirdrose** [mercadopago/cart-virtuemart#2]
Hello, I have installed the plugin, but on Step 3, i get redirected to www.sitename.com/index.php?option=com_virtuemart&view=virtuemart. The same thing happens when clicking on the payment method to edit configuration. 
Joomla version: 3.5.0
VirtueMart Version: 3.0.16

**Comment by gmatsuoka** [comment]
Hello, how are you?
We will analyze this error.
Thanks!
