### ISSUE TITLE
Varios problemas con sus soluciones

### ISSUE THREAD

**Issue by restodo** [mercadopago/cart-virtuemart#20]
Les paso varias soluciones a problemas en el plugin de Mercadopago para Virtuemart así luego de analizarlas las puedan implementar en el próximo release. Les adjunto mercadopago.php zipeado con todas estas modificaciones.
[mercadopago.php.zip](https://github.com/mercadopago/cart-virtuemart/files/517332/mercadopago.php.zip)

1) Mensaje de Error: The Payment method didn't find the used payment plugin (Ocurre por falta de la función plgVmOnSelectCheckPayment)

> > Hay que agregar la siguiente función.

```
/**
 * This event is fired after the payment method has been selected. It can be used to store
 * additional payment info in the cart.
 *
 * @author Max Milbers
 * @author Valérie isaksen
 *
 * @param VirtueMartCart $cart: the actual cart
 * @return null if the payment was not selected, true if the data is valid, error message if the data is not vlaid
 *
 */
public function plgVmOnSelectCheckPayment (VirtueMartCart $cart, &$msg) {

    return $this->OnSelectCheck ($cart);
}
```

2) Error: Luego de realizar el pedido y completar el pago en Mercadopago, no agrega el método de pago en el mail que se le envía al usuario ni en la lista de pedidos de la tienda.

> > Hay que agregar las siguientes funciones.

```
/**
 * This method is fired when showing the order details in the frontend.
 * It displays the method-specific data.
 *
 * @param integer $order_id The order ID
 * @return mixed Null for methods that aren't active, text (HTML) otherwise
 * @author Max Milbers
 * @author Valerie Isaksen
 */
public function plgVmOnShowOrderFEPayment ($virtuemart_order_id, $virtuemart_paymentmethod_id, &$payment_name) {

    $this->onShowOrderFE ($virtuemart_order_id, $virtuemart_paymentmethod_id, $payment_name);
}

/**
 * This method is fired when showing when priting an Order
 * It displays the the payment method-specific data.
 *
 * @param integer $_virtuemart_order_id The order ID
 * @param integer $method_id  method used for this order
 * @return mixed Null when for payment methods that were not selected, text (HTML) otherwise
 * @author Valerie Isaksen
 */
function plgVmonShowOrderPrintPayment ($order_number, $method_id) {

    return $this->onShowOrderPrint ($order_number, $method_id);
}
```

> > Luego modificar lo siguiente.

Antes:
        // //add order
        // $this->getPaymentCurrency($method);
        // $paymentCurrency = CurrencyDisplay::getInstance($method->payment_currency);
        // $total_payment_currency = round($paymentCurrency->convertCurrencyTo($method->payment_currency, $order['details']['BT']->order_total, FALSE), 2);
        //
        // $dbValues['payment_name'] = $this->renderPluginName($method);
        // $dbValues['order_number'] = $order['details']['BT']->order_number;
        // $dbValues['virtuemart_paymentmethod_id'] = $order['details']['BT']->virtuemart_paymentmethod_id;
        // $dbValues['cost_per_transaction'] = (!empty($method->cost_per_transaction) ? $method->cost_per_transaction : 0);
        // $dbValues['cost_percent_total'] = (!empty($method->cost_percent_total) ? $method->cost_percent_total : 0);
        // $dbValues['payment_currency'] = 'BRL';
        // $dbValues['payment_order_total'] = $total_payment_currency;
        // $dbValues['reference'] = $order['details']['BT']->virtuemart_order_id;
        //
        // // storing data order into plugin data table
        // $this->storePSPluginInternalData($dbValues);

Después:
        VmConfig::loadJLang('com_virtuemart',true);
        VmConfig::loadJLang('com_virtuemart_orders', TRUE);

```
    if (!class_exists ('VirtueMartModelOrders')) {
        require(VMPATH_ADMIN . DS . 'models' . DS . 'orders.php');
    }

    $this->getPaymentCurrency($payment_method);

    $dbValues['payment_name'] = $this->renderPluginName ($payment_method);
    $dbValues['order_number'] = $cart->order_number;
    $dbValues['virtuemart_paymentmethod_id'] = $cart->virtuemart_paymentmethod_id;
    $dbValues['cost_per_transaction'] = $payment_method->cost_per_transaction;
    $dbValues['cost_percent_total'] = $payment_method->cost_percent_total;
    $dbValues['payment_currency'] = $payment_method->payment_currency;
    $dbValues['payment_order_total'] = $cart->cartPrices['billTotal'];
    $dbValues['tax_id'] = $payment_method->tax_id;
    $this->storePSPluginInternalData ($dbValues);
```

3) Error: Productos con valor de más de $999 en Mercadopago solo muestra el primer número que aparece al lado del separador de miles.
Por ejemplo un producto de $ 1525,25 el valor a pagar en Mercadopago sería 1,52

> > Hay que modificar las siguientes líneas.

Antes:
        $total_order = (float) number_format($cart->cartPrices['billTotal']- $cart->cartPrices['salesPriceShipment'], 2);

Después:
        $total_order = (float) $cart->cartPrices['billTotal'] - (float) $cart->cartPrices['salesPriceShipment'];

Antes:
                "unit_price" => (float) number_format($product->prices['salesPrice'], 2)

Después:
                "unit_price" => (float) $product->prices['salesPrice']

Antes:
            $total_sum += (float) number_format($product->prices['salesPrice'], 2);

Después:
            $total_sum += (float) $product->prices['salesPrice'];

4) Error: En general las instalaciones de Joomla 3 + Virtuemart 3 utilizan el lenguaje es-ES

> > Creación de carpeta es-ES en Lenguaje, copiar el archivo de es-AR y luego renombrarlo a es-ES

**Comment by restodo** [comment]
Pudieron ver todas las modificaciones que les pasé para que el plugin funcione correctamente en Virtuemart? Vi que hace 2 días cerraron el otro issue que estaba abierto y en este ni se molestaron en contestarlo.
La idea es que el plugin que ofrecen funcione bien, por eso me tomé la molestia de pasarle todas las modificaciones necesarias para que todo el mundo las tenga.

**Comment by gmatsuoka** [comment]
Hola @restodo, 

Las mejorias fueran aplicadas en el pull request de numero #26 .

Muchas gracias!

**Comment by josenovo77** [comment]
@restodo ahi vi que tuviste el mismo problema que yo con los digitos, ahi implemento la solucion que pusiste.

**Comment by josenovo77** [comment]
@restodo sabes que implemente las modificaciones por el tema del precio (no toma cuando es superior a $999), pero no hubo cambios, yo estoy utilizando Mercado Pago 2.0.0, note que los codigos son distintos al    archivo que subiste (tambien probe utilizando ese archivo)

**Comment by restodo** [comment]
@josenovo77 no te sabría decir, las modificaciones son las que viste en este post. A mi me funciona bien.
