### ISSUE TITLE
Mercadoenvio

### ISSUE THREAD

**Issue by yaelduckwen** [mercadopago/cart-virtuemart#21]
Hola, tengo una consulta respecto al plugin para Virtuemart y su funcionalidad con MercadoEnvio, hay algún tipo de conexión?
Las compras que se pagan con MP a través de la plataforma, hay alguna forma de unificar los datos con MercadoEnvio?
Gracias!

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen , todo bien?

La integración de Mercado Envios está en nuestro backlog.

Sí, es posible. Sigue la documentación:
https://www.mercadopago.com.br/developers/es/solutions/payments/basic-checkout/use-mercadoenvios/

Slds,

**Comment by yaelduckwen** [comment]
Hola @gmatsuoka, esto lo había implementado pero hay veces en que el form de envío en el Lightbox y otras no. Siempre en sandbox y sin tocar una sola linea de código.
A que se puede deber?

Lo que implemente fue este cambio en mercadopago.php, en la versión 2.0 del plugin

```
// Shipments
//$preference["shipments"]["mode"] = "custom";
$preference["shipments"]["mode"] = "me2";
$preference["shipments"]["dimensions"] = "20x30x30,2000";
```

**Comment by yaelduckwen** [comment]
Hola @gmatsuoka 

Ademas de lo anterior comentado, tengo duda sobre la opción de elegir forma de entregas, porque solamente me deja que lo envíen, no me da la opción de retirar por el local, seguí las instrucciones de la documentación y quedo así
```
// Shipments
		$preference["shipments"]["mode"] = "me2";
		$preference["shipments"]["dimensions"] = "20x30x30,2000";
		$preference["shipments"]["local_pickup"] = "true";

```
Pero cuando pongo esa ultima linea el lightbox directamente no abre

En la imagen se ve como solo tengo una opción: 
![image](https://cloud.githubusercontent.com/assets/16963836/20905189/92160cc2-bb21-11e6-9d46-40e006f51ba7.png)

Muchas Gracias

**Comment by yaelduckwen** [comment]
@gmatsuoka alguna respuesta a esto ultimo?
