### ISSUE TITLE
Precio multiplicado

### ISSUE THREAD

**Issue by yaelduckwen** [mercadopago/cart-virtuemart#24]
Cuando se compran varias unidades de un producto virtuemart ya los multiplica y manda el precio final, pero el plugin de MP vuelve a multiplicarlo de nuevo.

Ejemplo

![image](https://cloud.githubusercontent.com/assets/16963836/20318605/9f0ccc3c-ab49-11e6-83c0-82a09749e9a9.png)

![image](https://cloud.githubusercontent.com/assets/16963836/20318591/93d395f8-ab49-11e6-8e05-4f30a3fb90af.png)

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen , todo bien?

Desculpa la demora!

Hice un pull request (numero #25 ), puedes actualizar el módulo y hacer nuevas pruebas ?

Muchas gracias!

Gabriel.

**Comment by yaelduckwen** [comment]
@gmatsuoka sigue funcionando mal, me suma los impuestos tambien de mala manera
el tema es que el total ya lo saca Virtuemart pero MP sigue pasando datos extra y sumando en vez de tomar el total ya calculado.

Actualmente tengo dos productos de $60 = $120 + un impuesto de $ 12. El total que muestra en VM es de $132, el correcto.
Cuando se abre el iframe de MP me vuelve a sumar el impuesto de $12 y me genera un total de $144

Por favor resolver esa suma porque no puedo utilizar reglas de impuestos si no.

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen , 

Hice un pull request fijando el caso ha explicado antes. Puedes probar?

Slds,

Gabriel.

**Comment by yaelduckwen** [comment]
Luego de varios testing parece que funciona correctamente. Si se presenta otro error te comentare, muchas gracias!

**Comment by gmatsuoka** [comment]
Perfecto!
