### ISSUE TITLE
No funciona / not working

### ISSUE THREAD

**Issue by dudafugaz** [mercadopago/cart-virtuemart#4]
Instalo el plugin, y cuando creo el método de pago... todo bien hasta que pongo "guardar" en la primer instancia para poder configurar la cuenta y todo.. 
Queda pensando hasta que me da un error 500.. 
Alguna idea de porque me esta pasando esto?

after Install the plugin, and when you make the method of payment ... all good until you put "save " in the first instance to set up the account and all ..
It is thinking forever until I get an error 500 ..
Any idea why is this happening ?

Gracias / Thanks

**Comment by gmatsuoka** [comment]
Hello @dudafugaz, how are you?
Recently we did a pull request resolving this error. Just download the new version here in github.
Thanks!
