### ISSUE TITLE
No me toma los datos de facturacion

### ISSUE THREAD

**Issue by yaelduckwen** [mercadopago/cart-virtuemart#6]
En la facturación de virtuemart están todos los datos cargados, pero cuando voy a la etapa final y se abre el iframe de mercado pago, no me toma ningún dato de facturación, solo el código postal

Alguna idea?

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen, todo bien?

Puedes enviar una pantalla con el flujo para que pueda entender mejor?

Muchas gracias!

**Comment by gmatsuoka** [comment]
Hola @yaelduckwen, todo bien?

Actualizamos el módulo recientemente, puedes probar por favor?

Muchas gracias!

**Comment by yaeru** [comment]
Pruebo y te cuento, muchas gracias

**Comment by yaeru** [comment]
Solucionado
