### ISSUE TITLE
Error al confirmar pago

### ISSUE THREAD

**Issue by yaeru** [mercadopago/cart-virtuemart#9]
Estoy trabajando en sandbox y cuando quiero pagar me tira el error "Tuvimos un problema, intenta nuevamente"
Me pasa tanto como con mi cuenta real como con cuenta invitado. Alguna idea de que es?

Desde ya, muchísimas gracias por la ayuda.

Adjunto captura
![image](https://cloud.githubusercontent.com/assets/8006634/16353051/09220fb2-3a4b-11e6-9f39-6a5afa6a9e60.png)

**Comment by gmatsuoka** [comment]
Hola @yaeru, todo bien?

Creo que es una inestabilidad en el entorno de tests (sandbox).

Si este error persiste, intente probar con los usuarios de testes en el entorno de producción.

Slds,

**Comment by gmatsuoka** [comment]
Hola @yaeru,

El erro persiste?

Slds,

**Comment by yaeru** [comment]
Si, persiste
